<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250308023736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment ALTER id TYPE INT');
        $this->addSql('ALTER TABLE comment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE feedback ALTER id TYPE INT');
        $this->addSql('ALTER TABLE feedback ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE feedback ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE upvote ALTER id TYPE INT');
        $this->addSql('ALTER TABLE upvote ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE upvote ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE feedback ALTER id TYPE INT');
        $this->addSql('ALTER TABLE feedback ALTER id SET DEFAULT feedback_id_seq');
        $this->addSql('ALTER TABLE feedback ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE upvote ALTER id TYPE INT');
        $this->addSql('ALTER TABLE upvote ALTER id SET DEFAULT upvote_id_seq');
        $this->addSql('ALTER TABLE upvote ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT user_id_seq');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER id TYPE INT');
        $this->addSql('ALTER TABLE comment ALTER id SET DEFAULT comment_id_seq');
        $this->addSql('ALTER TABLE comment ALTER id DROP IDENTITY');
    }
}
